# Intended to be used together with graylog.yaml (where the network is defined)
# docker stack deploy -c graylog.yaml --compose-file nginx.yaml <stack_name>
# https://docs.docker.com/engine/reference/commandline/stack_deploy
version: "3.8"

services:
  # NGINX: https://hub.docker.com/_/nginx
  nginx:
    image: nginx:alpine
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - ./cert-data/letsencrypt:/etc/letsencrypt
      - ./cert-data/acme-webroot:/var/www/html/acme-webroot
      - ./nginx/graylog.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/graylog_ssl.conf:/etc/nginx/graylog_ssl.conf:ro
    # networks:
    #   - graylog
